"""Adding softDelete for gallery table

Revision ID: ad1ce6a264f7
Revises: e19b09b1fb9c
Create Date: 2018-08-25 12:53:35.972210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1ce6a264f7'
down_revision = 'e19b09b1fb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gallery', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gallery', 'deleted')
    # ### end Alembic commands ###
