"""add gallery table

Revision ID: b301c337a119
Revises: 03cfa72b644c
Create Date: 2018-08-20 12:16:27.028120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b301c337a119'
down_revision = '03cfa72b644c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pic_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Gallery_pic_url'), 'Gallery', ['pic_url'], unique=False)
    op.create_index(op.f('ix_Gallery_title'), 'Gallery', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Gallery_title'), table_name='Gallery')
    op.drop_index(op.f('ix_Gallery_pic_url'), table_name='Gallery')
    op.drop_table('Gallery')
    # ### end Alembic commands ###
