"""adding timestamp for gallery column

Revision ID: e19b09b1fb9c
Revises: b301c337a119
Create Date: 2018-08-23 14:48:28.862360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19b09b1fb9c'
down_revision = 'b301c337a119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gallery', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_Gallery_timestamp'), 'Gallery', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gallery', 'timestamp')
    # op.drop_index(op.f('ix_Gallery_timestamp'), 'Gallery')
    # ### end Alembic commands ###
